In [1]:
import pandas as pd

In [5]:
df = pd.read_csv('bi_7.csv', index_col=0)

In [6]:
df.head()

,index,주소,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,승차승객합,하차승객합,lat,lng
0,263,서울특별시 강남구 개포1동,758,2648,328,1164,1086,3812,37.481769,127.057631
1,264,서울특별시 강남구 개포2동,1461,6345,685,2756,2146,9101,37.489601,127.068769
2,265,서울특별시 강남구 개포4동,4007,8191,1511,4108,5518,12299,37.478825,127.051520
3,266,서울특별시 강남구 개포동,11997,17117,4494,7637,16491,24754,37.478964,127.060928
4,267,서울특별시 강남구 논현2동,351,459,157,264,508,723,37.517292,127.037188

In [13]:
df[df['주소'] == '서울특별시 강서구 가양동']

,index,주소,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,승차승객합,하차승객합,lat,lng
69,332,서울특별시 강서구 가양동,2292,5012,1062,2597,3354,7609,37.564832,126.834241

In [17]:
df[df['주소'] == '서울특별시 성동구 금호동1가']

,index,주소,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,승차승객합,하차승객합,lat,lng
330,593,서울특별시 성동구 금호동1가,3792,6237,1519,3143,5311,9380,37.554364,127.024449

In [14]:
df.sort_values('승차승객합', ascending=False).head(20)

,index,주소,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,승차승객합,하차승객합,lat,lng
107,370,서울특별시 관악구 신림동,146934,99706,88750,63586,235684,163292,37.462618,126.938325
20,283,서울특별시 강남구 역삼동,107366,64621,60182,33869,167548,98490,37.499907,127.037393
148,411,서울특별시 구로구 구로동,76445,56111,46721,29576,123166,85687,37.495185,126.882064
102,365,서울특별시 관악구 봉천동,74203,73906,44526,45329,118729,119235,37.479408,126.953582
436,699,서울특별시 양천구 목동,76887,56120,31599,30388,108486,86508,37.537019,126.873530
262,525,서울특별시 마포구 서교동,63487,30671,40389,19078,103876,49749,37.553490,126.917730
8,271,서울특별시 강남구 대치동,74552,30740,20279,14583,94831,45323,37.499491,127.061053
485,748,서울특별시 영등포구 여의도동,63493,23531,30196,12728,93689,36259,37.517540,126.934531
425,688,서울특별시 송파구 잠실동,56368,34256,33489,16474,89857,50730,37.506127,127.084294
63,326,서울특별시 강북구 수유동,53932,56531,32515,35472,86447,92003,37.638733,127.008910
233,496,서울특별시 동작구 노량진동,55330,23689,30034,13694,85364,37383,37.511003,126.941633
255,518,서울특별시 마포구 동교동,48503,15004,32155,8167,80658,23171,37.557686,126.923487
319,582,서울특별시 서초구 서초동,57440,45521,21311,20709,78751,66230,37.487687,127.017427
180,443,서울특별시 노원구 상계동,49369,33560,27158,18428,76527,51988,37.674803,127.073062
313,576,서울특별시 서초구 방배동,47736,42804,26357,20780,74093,63584,37.479935,126.993460
488,751,서울특별시 영등포구 영등포동3가,45938,19201,25681,10305,71619,29506,37.517755,126.907807
51,314,서울특별시 강북구 미아동,44762,36655,26180,23213,70942,59868,37.626833,127.026908
450,713,서울특별시 양천구 신정동,46831,44533,22098,24432,68929,68965,37.516601,126.863871
286,549,서울특별시 서대문구 신촌동,44102,23428,23699,14150,67801,37578,37.559479,126.943584
13,276,서울특별시 강남구 삼성동,44096,31496,20416,14081,64512,45577,37.513985,127.056521

In [11]:
df.sort_values('하차승객합', ascending=False).head(20)

,index,주소,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,승차승객합,하차승객합,lat,lng
107,370,서울특별시 관악구 신림동,146934,99706,88750,63586,235684,163292,37.462618,126.938325
102,365,서울특별시 관악구 봉천동,74203,73906,44526,45329,118729,119235,37.479408,126.953582
20,283,서울특별시 강남구 역삼동,107366,64621,60182,33869,167548,98490,37.499907,127.037393
63,326,서울특별시 강북구 수유동,53932,56531,32515,35472,86447,92003,37.638733,127.008910
436,699,서울특별시 양천구 목동,76887,56120,31599,30388,108486,86508,37.537019,126.873530
148,411,서울특별시 구로구 구로동,76445,56111,46721,29576,123166,85687,37.495185,126.882064
287,550,서울특별시 서대문구 연희동,34346,44802,18867,28735,53213,73537,37.571798,126.932525
450,713,서울특별시 양천구 신정동,46831,44533,22098,24432,68929,68965,37.516601,126.863871
93,356,서울특별시 강서구 화곡동,38450,44036,20668,24482,59118,68518,37.538118,126.847102
319,582,서울특별시 서초구 서초동,57440,45521,21311,20709,78751,66230,37.487687,127.017427
313,576,서울특별시 서초구 방배동,47736,42804,26357,20780,74093,63584,37.479935,126.993460
443,706,서울특별시 양천구 신월동,16682,37435,8545,22651,25227,60086,37.519981,126.836555
476,739,서울특별시 영등포구 신길동,22661,39666,10841,20303,33502,59969,37.506248,126.913952
51,314,서울특별시 강북구 미아동,44762,36655,26180,23213,70942,59868,37.626833,127.026908
187,450,서울특별시 노원구 중계동,35838,35606,15300,18866,51138,54472,37.651440,127.083127
247,510,서울특별시 동작구 상도동,22109,33478,12722,20636,34831,54114,37.498990,126.937719
530,793,서울특별시 용산구 한남동,40299,32788,21623,19818,61922,52606,37.531179,127.006245
180,443,서울특별시 노원구 상계동,49369,33560,27158,18428,76527,51988,37.674803,127.073062
550,813,서울특별시 은평구 응암동,23363,32957,13639,18715,37002,51672,37.592665,126.920521
425,688,서울특별시 송파구 잠실동,56368,34256,33489,16474,89857,50730,37.506127,127.084294

In [30]:
import re
p = re.compile('[0-9]')

In [24]:
string_0 = '2234'
print(p.search(string_0))

None

In [31]:
list(df['주소'])

['서울특별시 강남구 개포1동',
 '서울특별시 강남구 개포2동',
 '서울특별시 강남구 개포4동',
 '서울특별시 강남구 개포동',
 '서울특별시 강남구 논현2동',
 '서울특별시 강남구 논현동',
 '서울특별시 강남구 대치1동',
 '서울특별시 강남구 대치2동',
 '서울특별시 강남구 대치동',
 '서울특별시 강남구 도곡1동',
 '서울특별시 강남구 도곡2동',
 '서울특별시 강남구 도곡동',
 '서울특별시 강남구 삼성1동',
 '서울특별시 강남구 삼성동',
 '서울특별시 강남구 세곡동',
 '서울특별시 강남구 수서동',
 '서울특별시 강남구 신사동',
 '서울특별시 강남구 압구정동',
 '서울특별시 강남구 역삼1동',
 '서울특별시 강남구 역삼2동',
 '서울특별시 강남구 역삼동',
 '서울특별시 강남구 율현동',
 '서울특별시 강남구 일원1동',
 '서울특별시 강남구 일원2동',
 '서울특별시 강남구 일원동',
 '서울특별시 강남구 일원본동',
 '서울특별시 강남구 자곡동',
 '서울특별시 강남구 청담동',
 '서울특별시 강동구 강일동',
 '서울특별시 강동구 고덕1동',
 '서울특별시 강동구 고덕2동',
 '서울특별시 강동구 고덕동',
 '서울특별시 강동구 길동',
 '서울특별시 강동구 둔촌1동',
 '서울특별시 강동구 둔촌2동',
 '서울특별시 강동구 둔촌동',
 '서울특별시 강동구 명일1동',
 '서울특별시 강동구 명일2동',
 '서울특별시 강동구 명일동',
 '서울특별시 강동구 상일동',
 '서울특별시 강동구 성내1동',
 '서울특별시 강동구 성내2동',
 '서울특별시 강동구 성내3동',
 '서울특별시 강동구 성내동',
 '서울특별시 강동구 암사1동',
 '서울특별시 강동구 암사3동',
 '서울특별시 강동구 암사동',
 '서울특별시 강동구 천호1동',
 '서울특별시 강동구 천호2동',
 '서울특별시 강동구 천호3동',
 '서울특별시 강동구 천호동',
 '서울특별시 강북구 미아동',
 '서울특별시 강북구 번1동',
 '서울특별시 강북구 번2동',
 '서울특별시 강북구 번3동',
 '서울특별시 강북구 번동',
 '서울특별시 강북구 삼각산동',
 '서울특별시 강북구 삼양동',
 '서울특별시 강북구 송중동',
 '서울특별시 강북구 송천동',
 '서울특별시 강북구 수유1동',
 '서울특별시 강북구 수유2동',
 '서울특별시 강북구 수유3동',
 '서울특별시 강북구 수유동',
 '서울특별시 강북구 우이동',
 '서울특별시 강북구 인수동',
 '서울특별시 강서구 가양1동',
 '서울특별시 강서구 가양2동',
 '서울특별시 강서구 가양3동',
 '서울특별시 강서구 가양동',
 '서울특별시 강서구 개화동',
 '서울특별시 강서구 공항동',
 '서울특별시 강서구 과해동',
 '서울특별시 강서구 내발산동',
 '서울특별시 강서구 등촌1동',
 '서울특별시 강서구 등촌2동',
 '서울특별시 강서구 등촌3동',
 '서울특별시 강서구 등촌동',
 '서울특별시 강서구 마곡동',
 '서울특별시 강서구 발산1동',
 '서울특별시 강서구 방화1동',
 '서울특별시 강서구 방화2동',
 '서울특별시 강서구 방화3동',
 '서울특별시 강서구 방화동',
 '서울특별시 강서구 염창동',
 '서울특별시 강서구 외발산동',
 '서울특별시 강서구 우장산동',
 '서울특별시 강서구 화곡1동',
 '서울특별시 강서구 화곡2동',
 '서울특별시 강서구 화곡3동',
 '서울특별시 강서구 화곡4동',
 '서울특별시 강서구 화곡6동',
 '서울특별시 강서구 화곡8동',
 '서울특별시 강서구 화곡동',
 '서울특별시 강서구 화곡본동',
 '서울특별시 관악구 낙성대동',
 '서울특별시 관악구 난곡동',
 '서울특별시 관악구 난향동',
 '서울특별시 관악구 남현동',
 '서울특별시 관악구 대학동',
 '서울특별시 관악구 미성동',
 '서울특별시 관악구 보라매동',
 '서울특별시 관악구 봉천동',
 '서울특별시 관악구 삼성동',
 '서울특별시 관악구 서림동',
 '서울특별시 관악구 서원동',
 '서울특별시 관악구 성현동',
 '서울특별시 관악구 신림동',
 '서울특별시 관악구 신사동',
 '서울특별시 관악구 신원동',
 '서울특별시 관악구 은천동',
 '서울특별시 관악구 인헌동',
 '서울특별시 관악구 조원동',
 '서울특별시 관악구 중앙동',
 '서울특별시 관악구 청룡동',
 '서울특별시 관악구 청림동',
 '서울특별시 관악구 행운동',
 '서울특별시 광진구 광장동',
 '서울특별시 광진구 구의1동',
 '서울특별시 광진구 구의2동',
 '서울특별시 광진구 구의3동',
 '서울특별시 광진구 구의동',
 '서울특별시 광진구 군자동',
 '서울특별시 광진구 능동',
 '서울특별시 광진구 자양1동',
 '서울특별시 광진구 자양2동',
 '서울특별시 광진구 자양3동',
 '서울특별시 광진구 자양4동',
 '서울특별시 광진구 자양동',
 '서울특별시 광진구 중곡1동',
 '서울특별시 광진구 중곡2동',
 '서울특별시 광진구 중곡3동',
 '서울특별시 광진구 중곡4동',
 '서울특별시 광진구 중곡동',
 '서울특별시 광진구 화양동',
 '서울특별시 구로구 가리봉동',
 '서울특별시 구로구 개봉1동',
 '서울특별시 구로구 개봉2동',
 '서울특별시 구로구 개봉3동',
 '서울특별시 구로구 개봉동',
 '서울특별시 구로구 고척1동',
 '서울특별시 구로구 고척2동',
 '서울특별시 구로구 고척동',
 '서울특별시 구로구 구로1동',
 '서울특별시 구로구 구로2동',
 '서울특별시 구로구 구로3동',
 '서울특별시 구로구 구로4동',
 '서울특별시 구로구 구로5동',
 '서울특별시 구로구 구로동',
 '서울특별시 구로구 궁동',
 '서울특별시 구로구 수궁동',
 '서울특별시 구로구 신도림동',
 '서울특별시 구로구 오류1동',
 '서울특별시 구로구 오류2동',
 '서울특별시 구로구 오류동',
 '서울특별시 구로구 온수동',
 '서울특별시 구로구 천왕동',
 '서울특별시 구로구 항동',
 '서울특별시 금천구 가산동',
 '서울특별시 금천구 독산1동',
 '서울특별시 금천구 독산2동',
 '서울특별시 금천구 독산3동',
 '서울특별시 금천구 독산4동',
 '서울특별시 금천구 독산동',
 '서울특별시 금천구 시흥1동',
 '서울특별시 금천구 시흥2동',
 '서울특별시 금천구 시흥3동',
 '서울특별시 금천구 시흥4동',
 '서울특별시 금천구 시흥5동',
 '서울특별시 금천구 시흥동',
 '서울특별시 노원구 공릉1동',
 '서울특별시 노원구 공릉2동',
 '서울특별시 노원구 공릉동',
 '서울특별시 노원구 상계10동',
 '서울특별시 노원구 상계1동',
 '서울특별시 노원구 상계2동',
 '서울특별시 노원구 상계3.4동',
 '서울특별시 노원구 상계5동',
 '서울특별시 노원구 상계6.7동',
 '서울특별시 노원구 상계9동',
 '서울특별시 노원구 상계동',
 '서울특별시 노원구 월계1동',
 '서울특별시 노원구 월계2동',
 '서울특별시 노원구 월계3동',
 '서울특별시 노원구 월계동',
 '서울특별시 노원구 중계1동',
 '서울특별시 노원구 중계2.3동',
 '서울특별시 노원구 중계동',
 '서울특별시 노원구 중계본동',
 '서울특별시 노원구 하계1동',
 '서울특별시 노원구 하계2동',
 '서울특별시 노원구 하계동',
 '서울특별시 도봉구 도봉1동',
 '서울특별시 도봉구 도봉2동',
 '서울특별시 도봉구 도봉동',
 '서울특별시 도봉구 방학1동',
 '서울특별시 도봉구 방학2동',
 '서울특별시 도봉구 방학3동',
 '서울특별시 도봉구 방학동',
 '서울특별시 도봉구 쌍문1동',
 '서울특별시 도봉구 쌍문2동',
 '서울특별시 도봉구 쌍문3동',
 '서울특별시 도봉구 쌍문4동',
 '서울특별시 도봉구 쌍문동',
 '서울특별시 도봉구 창1동',
 '서울특별시 도봉구 창2동',
 '서울특별시 도봉구 창3동',
 '서울특별시 도봉구 창4동',
 '서울특별시 도봉구 창5동',
 '서울특별시 도봉구 창동',
 '서울특별시 동대문구 답십리1동',
 '서울특별시 동대문구 답십리2동',
 '서울특별시 동대문구 답십리동',
 '서울특별시 동대문구 신설동',
 '서울특별시 동대문구 용두동',
 '서울특별시 동대문구 용신동',
 '서울특별시 동대문구 이문1동',
 '서울특별시 동대문구 이문2동',
 '서울특별시 동대문구 이문동',
 '서울특별시 동대문구 장안1동',
 '서울특별시 동대문구 장안2동',
 '서울특별시 동대문구 장안동',
 '서울특별시 동대문구 전농1동',
 '서울특별시 동대문구 전농2동',
 '서울특별시 동대문구 전농동',
 '서울특별시 동대문구 제기동',
 '서울특별시 동대문구 청량리동',
 '서울특별시 동대문구 회기동',
 '서울특별시 동대문구 휘경1동',
 '서울특별시 동대문구 휘경2동',
 '서울특별시 동대문구 휘경동',
 '서울특별시 동작구 노량진1동',
 '서울특별시 동작구 노량진2동',
 '서울특별시 동작구 노량진동',
 '서울특별시 동작구 대방동',
 '서울특별시 동작구 동작동',
 '서울특별시 동작구 본동',
 '서울특별시 동작구 사당1동',
 '서울특별시 동작구 사당2동',
 '서울특별시 동작구 사당3동',
 '서울특별시 동작구 사당4동',
 '서울특별시 동작구 사당5동',
 '서울특별시 동작구 사당동',
 '서울특별시 동작구 상도1동',
 '서울특별시 동작구 상도2동',
 '서울특별시 동작구 상도3동',
 '서울특별시 동작구 상도4동',
 '서울특별시 동작구 상도동',
 '서울특별시 동작구 신대방1동',
 '서울특별시 동작구 신대방2동',
 '서울특별시 동작구 신대방동',
 '서울특별시 동작구 흑석동',
 '서울특별시 마포구 공덕동',
 '서울특별시 마포구 대흥동',
 '서울특별시 마포구 도화동',
 '서울특별시 마포구 동교동',
 '서울특별시 마포구 망원1동',
 '서울특별시 마포구 망원2동',
 '서울특별시 마포구 망원동',
 '서울특별시 마포구 상수동',
 '서울특별시 마포구 상암동',
 '서울특별시 마포구 서강동',
 '서울특별시 마포구 서교동',
 '서울특별시 마포구 성산1동',
 '서울특별시 마포구 성산2동',
 '서울특별시 마포구 성산동',
 '서울특별시 마포구 신공덕동',
 '서울특별시 마포구 신수동',
 '서울특별시 마포구 아현동',
 '서울특별시 마포구 연남동',
 '서울특별시 마포구 염리동',
 '서울특별시 마포구 용강동',
 '서울특별시 마포구 중동',
 '서울특별시 마포구 창전동',
 '서울특별시 마포구 하중동',
 '서울특별시 마포구 합정동',
 '서울특별시 서대문구 남가좌1동',
 '서울특별시 서대문구 남가좌2동',
 '서울특별시 서대문구 남가좌동',
 '서울특별시 서대문구 냉천동',
 '서울특별시 서대문구 대신동',
 '서울특별시 서대문구 대현동',
 '서울특별시 서대문구 북가좌1동',
 '서울특별시 서대문구 북가좌2동',
 '서울특별시 서대문구 북가좌동',
 '서울특별시 서대문구 북아현동',
 '서울특별시 서대문구 신촌동',
 '서울특별시 서대문구 연희동',
 '서울특별시 서대문구 영천동',
 '서울특별시 서대문구 창천동',
 '서울특별시 서대문구 천연동',
 '서울특별시 서대문구 충정로2가',
 '서울특별시 서대문구 충정로3가',
 '서울특별시 서대문구 충현동',
 '서울특별시 서대문구 현저동',
 '서울특별시 서대문구 홍은1동',
 '서울특별시 서대문구 홍은2동',
 '서울특별시 서대문구 홍은동',
 '서울특별시 서대문구 홍제1동',
 '서울특별시 서대문구 홍제2동',
 '서울특별시 서대문구 홍제3동',
 '서울특별시 서대문구 홍제동',
 '서울특별시 서초구 내곡동',
 '서울특별시 서초구 반포1동',
 '서울특별시 서초구 반포2동',
 '서울특별시 서초구 반포3동',
 '서울특별시 서초구 반포4동',
 '서울특별시 서초구 반포동',
 '서울특별시 서초구 반포본동',
 '서울특별시 서초구 방배1동',
 '서울특별시 서초구 방배2동',
 '서울특별시 서초구 방배3동',
 '서울특별시 서초구 방배4동',
 '서울특별시 서초구 방배동',
 '서울특별시 서초구 방배본동',
 '서울특별시 서초구 서초1동',
 '서울특별시 서초구 서초2동',
 '서울특별시 서초구 서초3동',
 '서울특별시 서초구 서초4동',
 '서울특별시 서초구 서초동',
 '서울특별시 서초구 양재1동',
 '서울특별시 서초구 양재2동',
 '서울특별시 서초구 양재동',
 '서울특별시 서초구 염곡동',
 '서울특별시 서초구 우면동',
 '서울특별시 서초구 원지동',
 '서울특별시 서초구 잠원동',
 '서울특별시 성동구 금호1가동',
 '서울특별시 성동구 금호2.3가동',
 '서울특별시 성동구 금호4가동',
 '서울특별시 성동구 금호동1가',
 '서울특별시 성동구 금호동2가',
 '서울특별시 성동구 금호동3가',
 '서울특별시 성동구 금호동4가',
 '서울특별시 성동구 마장동',
 '서울특별시 성동구 사근동',
 '서울특별시 성동구 성수1가1동',
 '서울특별시 성동구 성수1가2동',
 '서울특별시 성동구 성수2가1동',
 '서울특별시 성동구 성수2가3동',
 '서울특별시 성동구 성수동1가',
 '서울특별시 성동구 성수동2가',
 '서울특별시 성동구 송정동',
 '서울특별시 성동구 옥수동',
 '서울특별시 성동구 왕십리2동',
 '서울특별시 성동구 왕십리도선동',
 '서울특별시 성동구 용답동',
 '서울특별시 성동구 응봉동',
 '서울특별시 성동구 하왕십리동',
 '서울특별시 성동구 행당1동',
 '서울특별시 성동구 행당2동',
 '서울특별시 성동구 행당동',
 '서울특별시 성동구 홍익동',
 '서울특별시 성북구 길음1동',
 '서울특별시 성북구 길음2동',
 '서울특별시 성북구 길음동',
 '서울특별시 성북구 돈암1동',
 '서울특별시 성북구 돈암2동',
 '서울특별시 성북구 돈암동',
 '서울특별시 성북구 동선동',
 '서울특별시 성북구 동선동2가',
 '서울특별시 성북구 동선동4가',
 '서울특별시 성북구 동소문동1가',
 '서울특별시 성북구 동소문동2가',
 '서울특별시 성북구 동소문동4가',
 '서울특별시 성북구 동소문동5가',
 '서울특별시 성북구 동소문동7가',
 '서울특별시 성북구 보문동',
 '서울특별시 성북구 보문동5가',
 '서울특별시 성북구 보문동7가',
 '서울특별시 성북구 삼선동',
 '서울특별시 성북구 삼선동2가',
 '서울특별시 성북구 삼선동3가',
 '서울특별시 성북구 삼선동4가',
 '서울특별시 성북구 삼선동5가',
 '서울특별시 성북구 상월곡동',
 '서울특별시 성북구 석관동',
 '서울특별시 성북구 성북동',
 '서울특별시 성북구 성북동1가',
 '서울특별시 성북구 안암동',
 '서울특별시 성북구 안암동1가',
 '서울특별시 성북구 안암동2가',
 '서울특별시 성북구 안암동5가',
 '서울특별시 성북구 월곡1동',
 '서울특별시 성북구 월곡2동',
 '서울특별시 성북구 장위1동',
 '서울특별시 성북구 장위2동',
 '서울특별시 성북구 장위3동',
 '서울특별시 성북구 장위동',
 '서울특별시 성북구 정릉1동',
 '서울특별시 성북구 정릉2동',
 '서울특별시 성북구 정릉3동',
 '서울특별시 성북구 정릉4동',
 '서울특별시 성북구 정릉동',
 '서울특별시 성북구 종암동',
 '서울특별시 성북구 하월곡동',
 '서울특별시 송파구 가락1동',
 '서울특별시 송파구 가락2동',
 '서울특별시 송파구 가락동',
 '서울특별시 송파구 가락본동',
 '서울특별시 송파구 거여1동',
 '서울특별시 송파구 거여2동',
 '서울특별시 송파구 거여동',
 '서울특별시 송파구 마천1동',
 '서울특별시 송파구 마천2동',
 '서울특별시 송파구 마천동',
 '서울특별시 송파구 문정1동',
 '서울특별시 송파구 문정2동',
 '서울특별시 송파구 문정동',
 '서울특별시 송파구 방이1동',
 '서울특별시 송파구 방이2동',
 '서울특별시 송파구 방이동',
 '서울특별시 송파구 삼전동',
 '서울특별시 송파구 석촌동',
 '서울특별시 송파구 송파1동',
 '서울특별시 송파구 송파2동',
 '서울특별시 송파구 송파동',
 '서울특별시 송파구 신천동',
 '서울특별시 송파구 오금동',
 '서울특별시 송파구 오륜동',
 '서울특별시 송파구 위례동',
 '서울특별시 송파구 잠실2동',
 '서울특별시 송파구 잠실3동',
 '서울특별시 송파구 잠실4동',
 '서울특별시 송파구 잠실6동',
 '서울특별시 송파구 잠실동',
 '서울특별시 송파구 잠실본동',
 '서울특별시 송파구 장지동',
 '서울특별시 송파구 풍납1동',
 '서울특별시 송파구 풍납2동',
 '서울특별시 송파구 풍납동',
 '서울특별시 양천구 목1동',
 '서울특별시 양천구 목2동',
 '서울특별시 양천구 목3동',
 '서울특별시 양천구 목4동',
 '서울특별시 양천구 목5동',
 '서울특별시 양천구 목동',
 '서울특별시 양천구 신월1동',
 '서울특별시 양천구 신월2동',
 '서울특별시 양천구 신월4동',
 '서울특별시 양천구 신월5동',
 '서울특별시 양천구 신월6동',
 '서울특별시 양천구 신월7동',
 '서울특별시 양천구 신월동',
 '서울특별시 양천구 신정1동',
 '서울특별시 양천구 신정2동',
 '서울특별시 양천구 신정3동',
 '서울특별시 양천구 신정4동',
 '서울특별시 양천구 신정6동',
 '서울특별시 양천구 신정7동',
 '서울특별시 양천구 신정동',
 '서울특별시 영등포구 당산1동',
 '서울특별시 영등포구 당산2동',
 '서울특별시 영등포구 당산동',
 '서울특별시 영등포구 당산동2가',
 '서울특별시 영등포구 당산동3가',
 '서울특별시 영등포구 당산동4가',
 '서울특별시 영등포구 당산동5가',
 '서울특별시 영등포구 당산동6가',
 '서울특별시 영등포구 대림1동',
 '서울특별시 영등포구 대림2동',
 '서울특별시 영등포구 대림3동',
 '서울특별시 영등포구 대림동',
 '서울특별시 영등포구 도림동',
 '서울특별시 영등포구 문래동',
 '서울특별시 영등포구 문래동2가',
 '서울특별시 영등포구 문래동3가',
 '서울특별시 영등포구 문래동4가',
 '서울특별시 영등포구 문래동5가',
 '서울특별시 영등포구 문래동6가',
 '서울특별시 영등포구 신길1동',
 '서울특별시 영등포구 신길3동',
 '서울특별시 영등포구 신길4동',
 '서울특별시 영등포구 신길5동',
 '서울특별시 영등포구 신길6동',
 '서울특별시 영등포구 신길7동',
 '서울특별시 영등포구 신길동',
 '서울특별시 영등포구 양평1동',
 '서울특별시 영등포구 양평2동',
 '서울특별시 영등포구 양평동1가',
 '서울특별시 영등포구 양평동3가',
 '서울특별시 영등포구 양평동4가',
 '서울특별시 영등포구 양평동5가',
 '서울특별시 영등포구 양평동6가',
 '서울특별시 영등포구 양화동',
 '서울특별시 영등포구 여의도동',
 '서울특별시 영등포구 여의동',
 '서울특별시 영등포구 영등포동',
 '서울특별시 영등포구 영등포동3가',
 '서울특별시 영등포구 영등포동4가',
 '서울특별시 영등포구 영등포동5가',
 '서울특별시 영등포구 영등포동6가',
 '서울특별시 영등포구 영등포동7가',
 '서울특별시 영등포구 영등포동8가',
 '서울특별시 영등포구 영등포본동',
 '서울특별시 용산구 갈월동',
 '서울특별시 용산구 남영동',
 '서울특별시 용산구 도원동',
 '서울특별시 용산구 동빙고동',
 '서울특별시 용산구 문배동',
 '서울특별시 용산구 보광동',
 '서울특별시 용산구 산천동',
 '서울특별시 용산구 서계동',
 '서울특별시 용산구 서빙고동',
 '서울특별시 용산구 신계동',
 '서울특별시 용산구 용문동',
 '서울특별시 용산구 용산2가동',
 '서울특별시 용산구 용산동1가',
 '서울특별시 용산구 용산동2가',
 '서울특별시 용산구 용산동5가',
 '서울특별시 용산구 용산동6가',
 '서울특별시 용산구 원효로1가',
 '서울특별시 용산구 원효로1동',
 '서울특별시 용산구 원효로2가',
 '서울특별시 용산구 원효로2동',
 '서울특별시 용산구 원효로3가',
 '서울특별시 용산구 원효로4가',
 '서울특별시 용산구 이촌1동',
 '서울특별시 용산구 이촌2동',
 '서울특별시 용산구 이촌동',
 '서울특별시 용산구 이태원1동',
 '서울특별시 용산구 이태원2동',
 '서울특별시 용산구 이태원동',
 '서울특별시 용산구 청암동',
 '서울특별시 용산구 청파동',
 '서울특별시 용산구 청파동2가',
 '서울특별시 용산구 한강로1가',
 '서울특별시 용산구 한강로2가',
 '서울특별시 용산구 한강로3가',
 '서울특별시 용산구 한강로동',
 '서울특별시 용산구 한남동',
 '서울특별시 용산구 효창동',
 '서울특별시 용산구 후암동',
 '서울특별시 은평구 갈현1동',
 '서울특별시 은평구 갈현2동',
 '서울특별시 은평구 갈현동',
 '서울특별시 은평구 구산동',
 '서울특별시 은평구 녹번동',
 '서울특별시 은평구 대조동',
 '서울특별시 은평구 불광1동',
 '서울특별시 은평구 불광2동',
 '서울특별시 은평구 불광동',
 '서울특별시 은평구 수색동',
 '서울특별시 은평구 신사1동',
 '서울특별시 은평구 신사2동',
 '서울특별시 은평구 신사동',
 '서울특별시 은평구 역촌동',
 '서울특별시 은평구 응암1동',
 '서울특별시 은평구 응암2동',
 '서울특별시 은평구 응암3동',
 '서울특별시 은평구 응암동',
 '서울특별시 은평구 증산동',
 '서울특별시 은평구 진관동',
 '서울특별시 종로구 가회동',
 '서울특별시 종로구 경운동',
 '서울특별시 종로구 계동',
 '서울특별시 종로구 관수동',
 '서울특별시 종로구 관훈동',
 '서울특별시 종로구 교남동',
 '서울특별시 종로구 교북동',
 '서울특별시 종로구 구기동',
 '서울특별시 종로구 명륜1가',
 '서울특별시 종로구 명륜2가',
 '서울특별시 종로구 명륜3가',
 '서울특별시 종로구 명륜4가',
 '서울특별시 종로구 묘동',
 '서울특별시 종로구 무악동',
 '서울특별시 종로구 부암동',
 '서울특별시 종로구 사직동',
 '서울특별시 종로구 삼청동',
 '서울특별시 종로구 세종로',
 '서울특별시 종로구 숭인1동',
 '서울특별시 종로구 숭인2동',
 '서울특별시 종로구 숭인동',
 '서울특별시 종로구 신문로1가',
 '서울특별시 종로구 안국동',
 '서울특별시 종로구 연건동',
 '서울특별시 종로구 예지동',
 '서울특별시 종로구 옥인동',
 '서울특별시 종로구 운니동',
 '서울특별시 종로구 원남동',
 '서울특별시 종로구 원서동',
 '서울특별시 종로구 이화동',
 '서울특별시 종로구 인사동',
 '서울특별시 종로구 인의동',
 '서울특별시 종로구 재동',
 '서울특별시 종로구 종로1.2.3.4가동',
 '서울특별시 종로구 종로1가',
 '서울특별시 종로구 종로2가',
 '서울특별시 종로구 종로3가',
 '서울특별시 종로구 종로4가',
 '서울특별시 종로구 종로5.6가동',
 '서울특별시 종로구 종로5가',
 '서울특별시 종로구 종로6가',
 '서울특별시 종로구 창신1동',
 '서울특별시 종로구 창신2동',
 '서울특별시 종로구 창신3동',
 '서울특별시 종로구 창신동',
 '서울특별시 종로구 청운동',
 '서울특별시 종로구 청운효자동',
 '서울특별시 종로구 체부동',
 '서울특별시 종로구 통인동',
 '서울특별시 종로구 평창동',
 '서울특별시 종로구 혜화동',
 '서울특별시 종로구 홍지동',
 '서울특별시 종로구 홍파동',
 '서울특별시 종로구 효제동',
 '서울특별시 중구 광희동',
 '서울특별시 중구 남대문로2가',
 '서울특별시 중구 남대문로3가',
 '서울특별시 중구 남대문로5가',
 '서울특별시 중구 남창동',
 '서울특별시 중구 다동',
 '서울특별시 중구 다산동',
 '서울특별시 중구 동화동',
 '서울특별시 중구 만리동2가',
 '서울특별시 중구 명동',
 '서울특별시 중구 방산동',
 '서울특별시 중구 봉래동2가',
 '서울특별시 중구 서소문동',
 '서울특별시 중구 소공동',
 '서울특별시 중구 신당5동',
 '서울특별시 중구 신당동',
 '서울특별시 중구 쌍림동',
 '서울특별시 중구 약수동',
 '서울특별시 중구 예장동',
 '서울특별시 중구 을지로1가',
 '서울특별시 중구 을지로2가',
 '서울특별시 중구 을지로3가',
 '서울특별시 중구 을지로4가',
 '서울특별시 중구 을지로5가',
 '서울특별시 중구 을지로6가',
 '서울특별시 중구 을지로동',
 '서울특별시 중구 의주로1가',
 '서울특별시 중구 장충동',
 '서울특별시 중구 장충동1가',
 '서울특별시 중구 장충동2가',
 '서울특별시 중구 저동1가',
 '서울특별시 중구 정동',
 '서울특별시 중구 중림동',
 '서울특별시 중구 충무로1가',
 '서울특별시 중구 충무로5가',
 '서울특별시 중구 태평로2가',
 '서울특별시 중구 필동',
 '서울특별시 중구 필동1가',
 '서울특별시 중구 필동2가',
 '서울특별시 중구 황학동',
 '서울특별시 중구 회현동',
 '서울특별시 중구 회현동2가',
 '서울특별시 중구 흥인동',
 '서울특별시 중랑구 망우3동',
 '서울특별시 중랑구 망우동',
 '서울특별시 중랑구 망우본동',
 '서울특별시 중랑구 면목2동',
 '서울특별시 중랑구 면목3.8동',
 '서울특별시 중랑구 면목4동',
 '서울특별시 중랑구 면목5동',
 '서울특별시 중랑구 면목7동',
 '서울특별시 중랑구 면목동',
 '서울특별시 중랑구 면목본동',
 '서울특별시 중랑구 묵1동',
 '서울특별시 중랑구 묵2동',
 '서울특별시 중랑구 묵동',
 '서울특별시 중랑구 상봉1동',
 '서울특별시 중랑구 상봉2동',
 '서울특별시 중랑구 상봉동',
 '서울특별시 중랑구 신내1동',
 '서울특별시 중랑구 신내2동',
 '서울특별시 중랑구 신내동',
 '서울특별시 중랑구 중화1동',
 '서울특별시 중랑구 중화2동',
 '서울특별시 중랑구 중화동']

In [33]:
tf_list = []
for i in list(df['주소']):
    print(p.search(i))
    if p.search(i) == None:
        tf_list.append(False)
    else: tf_list.append(True)

<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='4'>
None
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='3'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
None
<re.Match object; span=(11, 12), match='1'>
<re.Match object; span=(11, 12), match='2'>
<re.Match object; span=(11, 12), match='3'>
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='6'>
<re.Match object; span=(12, 13), match='8'>
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='5'>
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='5'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='5'>
<re.Match object; span=(12, 13), match='6'>
<re.Match object; span=(12, 13), match='9'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
<re.Match object; span=(11, 12), match='1'>
<re.Match object; span=(11, 12), match='2'>
<re.Match object; span=(11, 12), match='3'>
<re.Match object; span=(11, 12), match='4'>
<re.Match object; span=(11, 12), match='5'>
None
<re.Match object; span=(14, 15), match='1'>
<re.Match object; span=(14, 15), match='2'>
None
None
None
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
None
None
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='5'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
None
None
None
None
None
None
None
None
None
<re.Match object; span=(14, 15), match='1'>
<re.Match object; span=(14, 15), match='2'>
None
None
None
None
<re.Match object; span=(14, 15), match='1'>
<re.Match object; span=(14, 15), match='2'>
None
None
None
None
None
None
None
<re.Match object; span=(14, 15), match='2'>
<re.Match object; span=(14, 15), match='3'>
None
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='3'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='3'>
<re.Match object; span=(13, 14), match='4'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
None
<re.Match object; span=(13, 14), match='2'>
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='4'>
<re.Match object; span=(14, 15), match='1'>
<re.Match object; span=(14, 15), match='2'>
<re.Match object; span=(14, 15), match='4'>
<re.Match object; span=(14, 15), match='5'>
<re.Match object; span=(14, 15), match='7'>
None
<re.Match object; span=(13, 14), match='5'>
<re.Match object; span=(13, 14), match='7'>
None
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='3'>
<re.Match object; span=(13, 14), match='4'>
<re.Match object; span=(13, 14), match='5'>
None
None
None
<re.Match object; span=(13, 14), match='1'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='5'>
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
None
None
None
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='6'>
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(11, 12), match='1'>
<re.Match object; span=(11, 12), match='2'>
<re.Match object; span=(11, 12), match='3'>
<re.Match object; span=(11, 12), match='4'>
<re.Match object; span=(11, 12), match='5'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='5'>
<re.Match object; span=(12, 13), match='6'>
<re.Match object; span=(12, 13), match='7'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='6'>
<re.Match object; span=(12, 13), match='7'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
<re.Match object; span=(14, 15), match='2'>
<re.Match object; span=(14, 15), match='3'>
<re.Match object; span=(14, 15), match='4'>
<re.Match object; span=(14, 15), match='5'>
<re.Match object; span=(14, 15), match='6'>
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='3'>
None
None
None
<re.Match object; span=(14, 15), match='2'>
<re.Match object; span=(14, 15), match='3'>
<re.Match object; span=(14, 15), match='4'>
<re.Match object; span=(14, 15), match='5'>
<re.Match object; span=(14, 15), match='6'>
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='3'>
<re.Match object; span=(13, 14), match='4'>
<re.Match object; span=(13, 14), match='5'>
<re.Match object; span=(13, 14), match='6'>
<re.Match object; span=(13, 14), match='7'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(14, 15), match='1'>
<re.Match object; span=(14, 15), match='3'>
<re.Match object; span=(14, 15), match='4'>
<re.Match object; span=(14, 15), match='5'>
<re.Match object; span=(14, 15), match='6'>
None
None
None
None
<re.Match object; span=(15, 16), match='3'>
<re.Match object; span=(15, 16), match='4'>
<re.Match object; span=(15, 16), match='5'>
<re.Match object; span=(15, 16), match='6'>
<re.Match object; span=(15, 16), match='7'>
<re.Match object; span=(15, 16), match='8'>
None
None
None
None
None
None
None
None
None
None
None
None
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='5'>
<re.Match object; span=(13, 14), match='6'>
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='3'>
<re.Match object; span=(13, 14), match='4'>
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
None
None
None
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='1'>
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='3'>
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
None
None
None
None
None
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
None
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(13, 14), match='1'>
None
None
None
None
None
None
None
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='5'>
<re.Match object; span=(12, 13), match='5'>
<re.Match object; span=(12, 13), match='6'>
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
None
None
None
None
None
None
None
None
None
None
None
<re.Match object; span=(13, 14), match='2'>
<re.Match object; span=(13, 14), match='3'>
<re.Match object; span=(13, 14), match='5'>
None
None
None
None
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(12, 13), match='2'>
None
None
<re.Match object; span=(11, 12), match='5'>
None
None
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='5'>
<re.Match object; span=(12, 13), match='6'>
None
<re.Match object; span=(12, 13), match='1'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(11, 12), match='1'>
None
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='5'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(11, 12), match='1'>
<re.Match object; span=(11, 12), match='2'>
None
None
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='3'>
None
None
<re.Match object; span=(12, 13), match='2'>
<re.Match object; span=(12, 13), match='3'>
<re.Match object; span=(12, 13), match='4'>
<re.Match object; span=(12, 13), match='5'>
<re.Match object; span=(12, 13), match='7'>
None
None
<re.Match object; span=(11, 12), match='1'>
<re.Match object; span=(11, 12), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None
<re.Match object; span=(12, 13), match='1'>
<re.Match object; span=(12, 13), match='2'>
None

In [34]:
tf_list

[True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 False,
 True,
 False,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 False,
 True,
 False,
 True,
 False,
 False,
 True,
 True,
 True,
 True,
 True,
 False,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 False]

In [36]:
num_dong = df[tf_list]
num_dong.head()

,index,주소,22시승차총승객수,22시하차총승객수,23시승차총승객수,23시하차총승객수,승차승객합,하차승객합,lat,lng
0,263,서울특별시 강남구 개포1동,758,2648,328,1164,1086,3812,37.481769,127.057631
1,264,서울특별시 강남구 개포2동,1461,6345,685,2756,2146,9101,37.489601,127.068769
2,265,서울특별시 강남구 개포4동,4007,8191,1511,4108,5518,12299,37.478825,127.051520
4,267,서울특별시 강남구 논현2동,351,459,157,264,508,723,37.517292,127.037188
6,269,서울특별시 강남구 대치1동,12897,3907,2785,2019,15682,5926,37.493211,127.056742

In [38]:
num_dong.to_excel('jgw_num_dong.xlsx')

In [67]:
for i in list(num_dong['주소']):
    print(i.split()[-1], end=' :')
    d = i.split()[-1]
    for j in range(0, 10):
        d = d.replace(str(j), '')        
    d = d.replace('.','')
    print(d)

개포1동 :개포동
개포2동 :개포동
개포4동 :개포동
논현2동 :논현동
대치1동 :대치동
대치2동 :대치동
도곡1동 :도곡동
도곡2동 :도곡동
삼성1동 :삼성동
역삼1동 :역삼동
역삼2동 :역삼동
일원1동 :일원동
일원2동 :일원동
고덕1동 :고덕동
고덕2동 :고덕동
둔촌1동 :둔촌동
둔촌2동 :둔촌동
명일1동 :명일동
명일2동 :명일동
성내1동 :성내동
성내2동 :성내동
성내3동 :성내동
암사1동 :암사동
암사3동 :암사동
천호1동 :천호동
천호2동 :천호동
천호3동 :천호동
번1동 :번동
번2동 :번동
번3동 :번동
수유1동 :수유동
수유2동 :수유동
수유3동 :수유동
가양1동 :가양동
가양2동 :가양동
가양3동 :가양동
등촌1동 :등촌동
등촌2동 :등촌동
등촌3동 :등촌동
발산1동 :발산동
방화1동 :방화동
방화2동 :방화동
방화3동 :방화동
화곡1동 :화곡동
화곡2동 :화곡동
화곡3동 :화곡동
화곡4동 :화곡동
화곡6동 :화곡동
화곡8동 :화곡동
구의1동 :구의동
구의2동 :구의동
구의3동 :구의동
자양1동 :자양동
자양2동 :자양동
자양3동 :자양동
자양4동 :자양동
중곡1동 :중곡동
중곡2동 :중곡동
중곡3동 :중곡동
중곡4동 :중곡동
개봉1동 :개봉동
개봉2동 :개봉동
개봉3동 :개봉동
고척1동 :고척동
고척2동 :고척동
구로1동 :구로동
구로2동 :구로동
구로3동 :구로동
구로4동 :구로동
구로5동 :구로동
오류1동 :오류동
오류2동 :오류동
독산1동 :독산동
독산2동 :독산동
독산3동 :독산동
독산4동 :독산동
시흥1동 :시흥동
시흥2동 :시흥동
시흥3동 :시흥동
시흥4동 :시흥동
시흥5동 :시흥동
공릉1동 :공릉동
공릉2동 :공릉동
상계10동 :상계동
상계1동 :상계동
상계2동 :상계동
상계3.4동 :상계동
상계5동 :상계동
상계6.7동 :상계동
상계9동 :상계동
월계1동 :월계동
월계2동 :월계동
월계3동 :월계동
중계1동 :중계동
중계2.3동 :중계동
하계1동 :하계동
하계2동 :하계동
도봉1동 :도봉동
도봉2동 :도봉동
방학1동 :방학동
방학2동 :방학동
방학3동 :방학동
쌍문1동 :쌍문동
쌍문2동 :쌍문동
쌍문3동 :쌍문동
쌍문4동 :쌍문동
창1동 :창동
창2동 :창동
창3동 :창동
창4동 :창동
창5동 :창동
답십리1동 :답십리동
답십리2동 :답십리동
이문1동 :이문동
이문2동 :이문동
장안1동 :장안동
장안2동 :장안동
전농1동 :전농동
전농2동 :전농동
휘경1동 :휘경동
휘경2동 :휘경동
노량진1동 :노량진동
노량진2동 :노량진동
사당1동 :사당동
사당2동 :사당동
사당3동 :사당동
사당4동 :사당동
사당5동 :사당동
상도1동 :상도동
상도2동 :상도동
상도3동 :상도동
상도4동 :상도동
신대방1동 :신대방동
신대방2동 :신대방동
망원1동 :망원동
망원2동 :망원동
성산1동 :성산동
성산2동 :성산동
남가좌1동 :남가좌동
남가좌2동 :남가좌동
북가좌1동 :북가좌동
북가좌2동 :북가좌동
충정로2가 :충정로가
충정로3가 :충정로가
홍은1동 :홍은동
홍은2동 :홍은동
홍제1동 :홍제동
홍제2동 :홍제동
홍제3동 :홍제동
반포1동 :반포동
반포2동 :반포동
반포3동 :반포동
반포4동 :반포동
방배1동 :방배동
방배2동 :방배동
방배3동 :방배동
방배4동 :방배동
서초1동 :서초동
서초2동 :서초동
서초3동 :서초동
서초4동 :서초동
양재1동 :양재동
양재2동 :양재동
금호1가동 :금호가동
금호2.3가동 :금호가동
금호4가동 :금호가동
금호동1가 :금호동가
금호동2가 :금호동가
금호동3가 :금호동가
금호동4가 :금호동가
성수1가1동 :성수가동
성수1가2동 :성수가동
성수2가1동 :성수가동
성수2가3동 :성수가동
성수동1가 :성수동가
성수동2가 :성수동가
왕십리2동 :왕십리동
행당1동 :행당동
행당2동 :행당동
길음1동 :길음동
길음2동 :길음동
돈암1동 :돈암동
돈암2동 :돈암동
동선동2가 :동선동가
동선동4가 :동선동가
동소문동1가 :동소문동가
동소문동2가 :동소문동가
동소문동4가 :동소문동가
동소문동5가 :동소문동가
동소문동7가 :동소문동가
보문동5가 :보문동가
보문동7가 :보문동가
삼선동2가 :삼선동가
삼선동3가 :삼선동가
삼선동4가 :삼선동가
삼선동5가 :삼선동가
성북동1가 :성북동가
안암동1가 :안암동가
안암동2가 :안암동가
안암동5가 :안암동가
월곡1동 :월곡동
월곡2동 :월곡동
장위1동 :장위동
장위2동 :장위동
장위3동 :장위동
정릉1동 :정릉동
정릉2동 :정릉동
정릉3동 :정릉동
정릉4동 :정릉동
가락1동 :가락동
가락2동 :가락동
거여1동 :거여동
거여2동 :거여동
마천1동 :마천동
마천2동 :마천동
문정1동 :문정동
문정2동 :문정동
방이1동 :방이동
방이2동 :방이동
송파1동 :송파동
송파2동 :송파동
잠실2동 :잠실동
잠실3동 :잠실동
잠실4동 :잠실동
잠실6동 :잠실동
풍납1동 :풍납동
풍납2동 :풍납동
목1동 :목동
목2동 :목동
목3동 :목동
목4동 :목동
목5동 :목동
신월1동 :신월동
신월2동 :신월동
신월4동 :신월동
신월5동 :신월동
신월6동 :신월동
신월7동 :신월동
신정1동 :신정동
신정2동 :신정동
신정3동 :신정동
신정4동 :신정동
신정6동 :신정동
신정7동 :신정동
당산1동 :당산동
당산2동 :당산동
당산동2가 :당산동가
당산동3가 :당산동가
당산동4가 :당산동가
당산동5가 :당산동가
당산동6가 :당산동가
대림1동 :대림동
대림2동 :대림동
대림3동 :대림동
문래동2가 :문래동가
문래동3가 :문래동가
문래동4가 :문래동가
문래동5가 :문래동가
문래동6가 :문래동가
신길1동 :신길동
신길3동 :신길동
신길4동 :신길동
신길5동 :신길동
신길6동 :신길동
신길7동 :신길동
양평1동 :양평동
양평2동 :양평동
양평동1가 :양평동가
양평동3가 :양평동가
양평동4가 :양평동가
양평동5가 :양평동가
양평동6가 :양평동가
영등포동3가 :영등포동가
영등포동4가 :영등포동가
영등포동5가 :영등포동가
영등포동6가 :영등포동가
영등포동7가 :영등포동가
영등포동8가 :영등포동가
용산2가동 :용산가동
용산동1가 :용산동가
용산동2가 :용산동가
용산동5가 :용산동가
용산동6가 :용산동가
원효로1가 :원효로가
원효로1동 :원효로동
원효로2가 :원효로가
원효로2동 :원효로동
원효로3가 :원효로가
원효로4가 :원효로가
이촌1동 :이촌동
이촌2동 :이촌동
이태원1동 :이태원동
이태원2동 :이태원동
청파동2가 :청파동가
한강로1가 :한강로가
한강로2가 :한강로가
한강로3가 :한강로가
갈현1동 :갈현동
갈현2동 :갈현동
불광1동 :불광동
불광2동 :불광동
신사1동 :신사동
신사2동 :신사동
응암1동 :응암동
응암2동 :응암동
응암3동 :응암동
명륜1가 :명륜가
명륜2가 :명륜가
명륜3가 :명륜가
명륜4가 :명륜가
숭인1동 :숭인동
숭인2동 :숭인동
신문로1가 :신문로가
종로1.2.3.4가동 :종로가동
종로1가 :종로가
종로2가 :종로가
종로3가 :종로가
종로4가 :종로가
종로5.6가동 :종로가동
종로5가 :종로가
종로6가 :종로가
창신1동 :창신동
창신2동 :창신동
창신3동 :창신동
남대문로2가 :남대문로가
남대문로3가 :남대문로가
남대문로5가 :남대문로가
만리동2가 :만리동가
봉래동2가 :봉래동가
신당5동 :신당동
을지로1가 :을지로가
을지로2가 :을지로가
을지로3가 :을지로가
을지로4가 :을지로가
을지로5가 :을지로가
을지로6가 :을지로가
의주로1가 :의주로가
장충동1가 :장충동가
장충동2가 :장충동가
저동1가 :저동가
충무로1가 :충무로가
충무로5가 :충무로가
태평로2가 :태평로가
필동1가 :필동가
필동2가 :필동가
회현동2가 :회현동가
망우3동 :망우동
면목2동 :면목동
면목3.8동 :면목동
면목4동 :면목동
면목5동 :면목동
면목7동 :면목동
묵1동 :묵동
묵2동 :묵동
상봉1동 :상봉동
상봉2동 :상봉동
신내1동 :신내동
신내2동 :신내동
중화1동 :중화동
중화2동 :중화동